"""empty message

Revision ID: f0bac72e0f4d
Revises: 
Create Date: 2022-11-13 19:19:36.646712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0bac72e0f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Schedule')
    op.drop_table('Group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Group',
    sa.Column('group_id', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Schedule',
    sa.Column('schedule_id', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('schedule_name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='Schedule_ibfk_1'),
    sa.PrimaryKeyConstraint('schedule_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('user_id', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('group_id', mysql.VARCHAR(length=25), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Group.group_id'], name='User_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
